import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  BAND_ORDER,
  ExportVerdict,
  buildEntry,
  type Band,
  type QueueEntry,
} from "../src/review-queue.js";
import type { SymbolRecord } from "../src/types.js";

/**
 * Writes the ordered review worklist.
 *
 * 563 opaque JSON files give a reviewer nowhere to start, which is why none of
 * them have been reviewed. This joins the two signals already computed and
 * sorts the work so the cheap, high-yield records come first.
 */

const DATA_DIRS = ["advisories", "proposals"] as const;
const EXPORT_CHECK_PATH = "study/export-check.json";
const QUEUE_JSON_PATH = "study/review-queue.json";
const QUEUE_DOC_PATH = "docs/review-queue.md";
const JSON_EXTENSION = ".json";
const JSON_INDENT = 2;

interface ExportCheckRow {
  readonly id: string;
  readonly verdict: string;
}

const BAND_TITLES: Record<Band, string> = {
  likely_wrong: "Likely wrong",
  conflicting: "Conflicting signals",
  likely_right: "Likely right",
  weak_support: "Weak support",
  unsupported: "Unsupported",
};

const BAND_GUIDANCE: Record<Band, string> = {
  likely_wrong:
    "Start here. Both signals are negative. Confirm the symbol is wrong, delete the record, " +
    "and add a regression test to `tests/extract-symbols.test.ts` so the extractor stops " +
    "producing that shape. Every rejection here raises precision permanently.",
  conflicting:
    "The two signals disagree, so this is where judgement is actually required. Read the " +
    "advisory and the fix commit, and decide.",
  likely_right:
    "Both signals agree. Skim, confirm the named symbol really is the vulnerable one rather " +
    "than merely a real export, then promote to `advisories/` with `reviewedBy` and `reviewedAt`.",
  weak_support:
    "One signal is positive and the other is silent. A light check, usually quick.",
  unsupported:
    "Nothing is known either way. Slowest to review, so leave these until last.",
};

function loadExportVerdicts(): Map<string, ExportVerdict[]> {
  const byId = new Map<string, ExportVerdict[]>();
  let rows: ExportCheckRow[] = [];
  try {
    rows = JSON.parse(readFileSync(EXPORT_CHECK_PATH, "utf8")) as ExportCheckRow[];
  } catch {
    return byId;
  }
  for (const row of rows) {
    const verdict = Object.values(ExportVerdict).find(value => value === row.verdict);
    const existing = byId.get(row.id) ?? [];
    existing.push(verdict ?? ExportVerdict.Unknown);
    byId.set(row.id, existing);
  }
  return byId;
}

function loadRecords(): SymbolRecord[] {
  const records: SymbolRecord[] = [];
  for (const dir of DATA_DIRS) {
    for (const name of readdirSync(dir).filter(f => f.endsWith(JSON_EXTENSION))) {
      records.push(JSON.parse(readFileSync(path.join(dir, name), "utf8")) as SymbolRecord);
    }
  }
  return records;
}

/** Groups entries by band, preserving the presentation order. */
function groupByBand(entries: readonly QueueEntry[]): Map<Band, QueueEntry[]> {
  const grouped = new Map<Band, QueueEntry[]>();
  for (const band of BAND_ORDER) {
    grouped.set(band, []);
  }
  for (const entry of entries) {
    grouped.get(entry.band)?.push(entry);
  }
  return grouped;
}

function renderRow(entry: QueueEntry): string {
  const packages = entry.packages.slice(0, 2).join(", ");
  const more = entry.packages.length > 2 ? ` +${entry.packages.length - 2}` : "";
  return `| \`${entry.id}\` | ${packages}${more} | \`${entry.symbols.join("`, `")}\` |`;
}

function renderDoc(grouped: Map<Band, QueueEntry[]>, total: number): string {
  const lines: string[] = [
    "---",
    "id: review-queue",
    "title: Review queue",
    "sidebar_label: Review queue",
    "sidebar_position: 3",
    "---",
    "",
    "Generated by `scripts/build-review-queue.ts`. Do not edit by hand.",
    "",
    "Every record here is machine-proposed and unreviewed. Two independent signals are",
    "combined to sort them: whether the package actually exports the named symbol, and",
    "whether the fix commit's diff mentions it. Neither settles a record alone, but",
    "together they say where a reviewer's attention repays most.",
    "",
    `**${total} records.** Bands are ordered by yield, not severity.`,
    "",
    "| Band | Records | What it means |",
    "|---|---|---|",
  ];

  for (const band of BAND_ORDER) {
    const entries = grouped.get(band) ?? [];
    lines.push(
      `| [${BAND_TITLES[band]}](#${anchorFor(BAND_TITLES[band])}) | ${entries.length} | ${firstSentence(BAND_GUIDANCE[band])} |`,
    );
  }

  for (const band of BAND_ORDER) {
    const entries = grouped.get(band) ?? [];
    lines.push("", `## ${BAND_TITLES[band]}`, "", `${entries.length} records. ${BAND_GUIDANCE[band]}`, "");
    if (entries.length === 0) {
      lines.push("None.");
      continue;
    }
    lines.push("| Advisory | Package | Symbols |", "|---|---|---|");
    for (const entry of entries) {
      lines.push(renderRow(entry));
    }
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Derives a heading anchor from the heading text, not the band key.
 *
 * Deriving it from the key produced `#conflicting` for a heading rendered as
 * "Conflicting signals", so the contents link went nowhere.
 */
function anchorFor(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

function firstSentence(text: string): string {
  const stop = text.indexOf(". ");
  return stop === -1 ? text : text.slice(0, stop + 1).trim();
}

function run(): void {
  const verdicts = loadExportVerdicts();
  const entries = loadRecords()
    .map(record => buildEntry(record, verdicts.get(record.id) ?? [ExportVerdict.Unknown]))
    .sort((a, b) => a.id.localeCompare(b.id));

  const grouped = groupByBand(entries);
  writeFileSync(QUEUE_JSON_PATH, `${JSON.stringify(entries, null, JSON_INDENT)}\n`, "utf8");
  writeFileSync(QUEUE_DOC_PATH, renderDoc(grouped, entries.length), "utf8");

  for (const band of BAND_ORDER) {
    const count = grouped.get(band)?.length ?? 0;
    process.stdout.write(`${BAND_TITLES[band].padEnd(20)} ${String(count).padStart(4)}\n`);
  }
  process.stdout.write(`${"total".padEnd(20)} ${String(entries.length).padStart(4)}\n`);
  process.stdout.write(`\nwritten: ${QUEUE_DOC_PATH}, ${QUEUE_JSON_PATH}\n`);
}

run();
